name: Draw ZMK keymaps
on:
  workflow_dispatch: # allows manual run
  push:
    paths:
      - "config/*.keymap"
      - "config/*.json"
      - ".github/workflows/draw-keymap.yml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write # allow workflow to commit the SVG to the repo
    with:
      keymap_patterns: "config/piantor_pro_bt.keymap"
      output_folder: "keymap-drawer" # results will be saved here
      parse_args: "piantor_pro_bt:'-c 6'" # tells it the layout has 6 columns per side
